config/routes.rb
Rails.application.routes.draw do
  resources :questions do
    resources :answers
    
  end
  get "k/matte"=>"pages#matte"
  get "k/naturfag"=>"pages#naturfag"
  get "k/engelsk"=>"pages#engelsk"
  get "k/samfunnsfag"=>"pages#samfunnsfag"
  get "k/rle"=>"pages#rle"
  get "k/norsk"=>"pages#norsk"
  
  devise_for :users
  root 'pages#home'

  
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :questions
  
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
    @answers = Answer.all.reverse_order
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    question = Question.find(params[:question_id])
    @answer = question.answers.create(answer_params)
    
    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer.question, :notice => 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:body,:user_id,:question_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def matte
    @questions = Question.all.where(category:"Matte")
  end
  
  def naturfag
    @questions = Question.all.where(category:"Naturfag")
  end
  
  def engelsk
    @questions = Question.all.where(category:"Engelsk")
  end

  def samfunnsfag
    @questions = Question.all.where(category:"Samfunnsfag")
  end
  
  def rle
    @questions = Question.all.where(category:"RLE")
  end
  
  def norsk
    @questions = Question.all.where(category:"Norsk")
  end
  
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]


   before_action :authenticate_user!, except: [:index, :show]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all.reverse_order
    
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    question = Question.find(params[:id])
    
    @answers = question.answers.reverse_order
  end

  # GET /questions/new
  def new
    @question = current_user.questions.build
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = current_user.questions.create(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:body, :category, :user_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
def resource_name
    :user
  end

  def resource_class 
     User 
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_form.html.erb
<center>
<%= form_for([@answer.question, @answer]) do |form| %>
<div class="jumbotron">
  <div class="container" style="max-width: 600px">
  
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.hidden_field :body, class: 'form-control input-lg', id: 'answer_body' %>
    <trix-editor style="background-color: #fff; min-height: 300px; text-align: left" input="answer_body"></trix-editor>
  </div>

  
  <div class="form-group">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="form-group">
    <%= form.submit 'Submit Answer' ,class: "btn btn-succsess btn-lg" %>
  </div>
  </div>
</div>
<% end %>
</center>

app/views/answers/edit.html.erb
<h1>editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Question</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.body %></td>
        <td><%= answer.question %></td>
        <td><%= answer.user %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<center>
<h1>Nytt svar</h1>

<%= render 'form', answer: @answer %>

</center>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @answer.body %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer.question %>
</p>

<p>
  <strong>User:</strong>
  <%= @answer.user %>
</p>

<%= link_to 'edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Svara</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="google-site-verification" content="grqqO-Ewe7z8_2MjZoX6zSU7YVAG9o46oM1UrwA90uI" />
     <meta name="description" content="Et sted hvor elever deler kunnskap og samarbeider">
  <meta name="keywords" content="Lekser,Skolearbeid,Leksehjelp,Skole,elev,utdanning,Fag">
  </head>


  <body>
    <%= render "shared/navbar" %>
 
    <%= yield %>
    
    
    <div class="footer" style="margin-bottom: -10px; padding-top: 10px; padding-bottom: 10px">
	    <%= render "shared/footer" %>
	
  </body>
</html>

app/views/pages/engelsk.html.erb
<p id="notice"><%= notice %></p>



<center>
<% @questions.each do |question| %>
<div class="jumbotron">
  <div class="container">
    <h3><%= link_to question.body, question %></h3>
    <h4>Spurt av <%= question.user.username %> in <span class="question-category"><%= question.category %></h4></span> 
    
    <%= link_to 'Svar', new_question_answer_path(question), class: "btn btn-danger btn-sm" %>
    <%= link_to 'se på svarene',question, class: "btn btn-danger btn-sm" %>
    <% if user_signed_in? %>
    <% if current_user.id == question.user.id %>
      <div>
        <%= link_to 'edit', edit_question_path(question), class: 'btn btn-warning btn-xs' %>
        <%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-warning btn-xs' %>
      </div>
    <% end %> 
    <% end %>
  </div>
</div>
<% end %>
</center>
        

app/views/pages/home.html.erb
<header class="header-image" style="margin-top: -50px">
  <meta name="google-site-verification" content="grqqO-Ewe7z8_2MjZoX6zSU7YVAG9o46oM1UrwA90uI" />
    <div class="headline">
        <div class="container">
            <div class="col-md-8">
                <h2 style="Arial,Helvetica,sans-serif;">Svara</h2>
                <center><h3 style="font-family: 'Nunito', sans-serif";>Et sted hvor elever deler kunnskap og samarbeider</h3></center>
        
            </div>
            <% if !user_signed_in? %>  
            <div class="col-md-4">
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h3 class="panel-title">Registrer deg</h3>
                  </div>
                  <div class="panel-body">
                    
                  
                    <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
                      <%= devise_error_messages! %>
                    
                      <div class="form-group">
                        <%= f.email_field :email, placeholder: 'Epost', class: 'form-control input-md' %>
                      </div>
                      
                      <div class="form-group">
                        <%= f.text_field :username, placeholder: 'Brukernavn', class: 'form-control input-md' %>
                      </div>
                    
                      <div class="form-group">
                        <%= f.password_field :password, placeholder: 'Passord', class: 'form-control input-md' %>
                      </div>
                    
                      <div class="form-group">
                        <%= f.password_field :password_confirmation, placeholder: 'Bekreft passord', class: 'form-control input-md' %>
                      </div>
                    
                      <div class="form-group">
                        <%= f.submit "Registrer deg", class: 'btn btn-primary btn-md' %>
                      </div>
                   
                    <% end %>
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
                    
  <% if user_signed_in? %>
  <div class="col-md-4">
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h3 class="panel-title">Nytt Spørsmål</h3>
                  </div>
                <div class="panel-body">
  
                <div class="form-group">
     
                <div class="form-group">
                 <%= form.text_field :body, class: 'form-control input-lg',placeholder: "Hva er 2+2" %>
                 </div>
                      
                      
                      
                      
                 <div class="form-group">
                  <%= form.select :category, [["Matte", "Matte"],["Naturfag", "Naturfag"],["Engelsk", "Engelsk"], ["Samfunnsfag", "Samfunnsfag"],["RLE", "RLE"] ,["Norsk", "Norsk"]], class: 'form-control input-lg' %>
                  </div>
  
                  <div class="form-group">
                   <%= form.submit "Spør spørsmål", class: "btn btn-primary btn-lg" %>
                   </div>
                 
  
  <div class="form-group">
 <%= form.text_field :body, class: 'form-control input-lg',placeholder: "Hva er 2+2" %>
                      
                      <%= link_to "Spør spørsmål", @questions_path %>

<%= link_to 'Back', questions_path %>
</div>

                   <% end %>
  
               
                      </div>
                      
                  
                    
                    
                  </div>
                </div>
            </div>
            <% end %>
        </div>
    </div>
</header>

app/views/pages/matte.html.erb
<p id="notice"><%= notice %></p>



<center>
<% @questions.each do |question| %>
<div class="jumbotron">
  <div class="container">
    <h3><%= link_to question.body, question %></h3>
    <h4>Spurt av <%= question.user.username %> in <span class="question-category"><%= question.category %></h4></span> 
    
    <%= link_to 'Svar', new_question_answer_path(question), class: "btn btn-danger btn-sm" %>
    <%= link_to 'se på svarene',question, class: "btn btn-danger btn-sm" %>
    <% if user_signed_in? %>
    <% if current_user.id == question.user.id %>
      <div>
        <%= link_to 'edit', edit_question_path(question), class: 'btn btn-warning btn-xs' %>
        <%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-warning btn-xs' %>
      </div>
    <% end %>  
    <% end %>
  </div>
</div>
<% end %>
</center>
        

app/views/pages/naturfag.html.erb
<p id="notice"><%= notice %></p>



<center>
<% @questions.each do |question| %>
<div class="jumbotron">
  <div class="container">
    <h3><%= link_to question.body, question %></h3>
    <h4>Spurt av <%= question.user.username %> in <span class="question-category"><%= question.category %></h4></span> 
    
    <%= link_to 'Svar', new_question_answer_path(question), class: "btn btn-danger btn-sm" %>
    <%= link_to 'se på svarene',question, class: "btn btn-danger btn-sm" %>
    <% if user_signed_in? %>
    <% if current_user.id == question.user.id %>
      <div>
        <%= link_to 'edit', edit_question_path(question), class: 'btn btn-warning btn-xs' %>
        <%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-warning btn-xs' %>
      </div>
    <% end %>  
    <% end %>
  </div>
</div>
<% end %>
</center>
        

app/views/pages/norsk.html.erb
<center>
<% @questions.each do |question| %>
<div class="jumbotron">
  <div class="container">
    <h3><%= link_to question.body, question %></h3>
    <h4>Spurt av <%= question.user.username %> in <span class="question-category"><%= question.category %></h4></span> 
    
    <%= link_to 'Svar', new_question_answer_path(question), class: "btn btn-danger btn-sm" %>
    <%= link_to 'se på svarene',question, class: "btn btn-danger btn-sm" %>
    <% if user_signed_in? %>
    <% if current_user.id == question.user.id %>
      <div>
        <%= link_to 'edit', edit_question_path(question), class: 'btn btn-warning btn-xs' %>
        <%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-warning btn-xs' %>
      </div>
    <% end %>
    <% end %>
  </div>
</div>
<% end %>
</center>
        

app/views/pages/rle.html.erb
<p id="notice"><%= notice %></p>



<center>
<% @questions.each do |question| %>
<div class="jumbotron">
  <div class="container">
    <h3><%= link_to question.body, question %></h3>
    <h4>Spurt av <%= question.user.username %> in <span class="question-category"><%= question.category %></h4></span> 
    
    <%= link_to 'Svar', new_question_answer_path(question), class: "btn btn-danger btn-sm" %>
    <%= link_to 'se på svarene',question, class: "btn btn-danger btn-sm" %>
    <% if user_signed_in? %>
    <% if current_user.id == question.user.id %>
      <div>
        <%= link_to 'edit', edit_question_path(question), class: 'btn btn-warning btn-xs' %>
        <%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-warning btn-xs' %>
      </div>
    <% end %>  
    <% end %>
  </div>
</div>
<% end %>
</center>
        

app/views/pages/samfunnsfag.html.erb
<p id="notice"><%= notice %></p>



<center>
<% @questions.each do |question| %>
<div class="jumbotron">
  <div class="container">
    <h3><%= link_to question.body, question %></h3>
    <h4>Spurt av <%= question.user.username %> in <span class="question-category"><%= question.category %></h4></span> 
    
    <%= link_to 'Svar', new_question_answer_path(question), class: "btn btn-danger btn-sm" %>
    <%= link_to 'se på svarene',question, class: "btn btn-danger btn-sm" %>
    <% if user_signed_in? %>
    <% if current_user.id == question.user.id %>
      <div>
        <%= link_to 'edit', edit_question_path(question), class: 'btn btn-warning btn-xs' %>
        <%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-warning btn-xs' %>
      </div>
    <% end %>  
    <% end %>
  </div>
</div>
<% end %>
</center>
        

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
   
    <%= form.text_field :body, class: 'form-control input-lg',placeholder: "Hva er 2+2" %>
  </div>

  <div class="form-group">
    
    <%= form.select :category, [["Matte", "Matte"],["Naturfag", "Naturfag"],["Engelsk", "Engelsk"], ["Samfunnsfag", "Samfunnsfag"],["RLE", "RLE"] ,["Norsk", "Norsk"]], class: 'form-control input-lg' %>
  </div>

  
  <div class="form-group">
    <%= form.submit "Spør spørsmål", class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>



<center>
<% @questions.each do |question| %>
<div class="jumbotron">
  <div class="container">
    <h3><%= link_to question.body, question %></h3>
    <h4>Spurt av <%= question.user.username %> in <span class="question-category"><%= question.category %></h4></span> 
    
    <%= link_to 'Svar', new_question_answer_path(question), class: "btn btn-danger btn-lg" %>
    <%= link_to 'Se på svarene',question, class: "btn btn-success btn-lg" %>
    <% if user_signed_in? %>
    <% if current_user.id == question.user.id %>
      <div>
        <%= link_to 'edit', edit_question_path(question), class: 'btn btn-warning btn-xs' %>
        <%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-warning btn-xs' %>
      </div>
    <% end %>  
    <% end %>
  </div>
</div>
<% end %>
</center>
        

app/views/questions/new.html.erb
<div>
<div style="max-width: 600px; margin: 0 auto">
<h1>Nytt Spørsmål</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>
</div>
</div>

app/views/questions/show.html.erb
<center>
   
<p id="notice"><%= notice %> </p>

<h1 style="color: #ff0000"><%= @question.body %></h1>

<h3>Spurt av <%= @question.user.username %> in <%= @question.category %></h3>

<%= link_to 'Svar', new_question_answer_path(@question),class: "btn btn-danger btn-lg" %>

<% @answers.each do |answer| %>
    <div style="background-color: #fff; max-width: 500px; text-align: left; padding: 20px 20px; margin: 10px 10px;border: 5px solid red;">
        <p><%= sanitize answer.body %></p>
        <h4>Besvart av <%= answer.user.username %></h4>
    </div>
<% end %>
</div>
</center>

app/views/shared/_footer.html.erb
<center>© Copyright Aman Aset 2018 !Development still in progress!</center>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%=link_to root_path do %>
      <%= image_tag 'svara.png' , width: '100px' %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left">
        <div class="form-group">
        
        </div>
        
        
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Fag <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Matte", k_matte_path %></li>
            <li><%= link_to "Samfunnsfag", k_samfunnsfag_path %></li>
            <li><%= link_to "Engelsk", k_engelsk_path %></li>
            <li><%= link_to "RLE", k_rle_path %></li>
            <li><%= link_to "Norsk", k_norsk_path %></li>
            <li><%= link_to "Naturfag", k_naturfag_path %></li>
          </ul>
        </li>
        <% if(!user_signed_in?) %>
          <li>
    
             
            <li>
<%= link_to 'Registrer deg', new_user_registration_path %>
          </li>
          <li>
            <%= link_to 'Logg inn', new_user_session_path %>
            
          </li>
        <% else %>
        <li><%= link_to 'Spør Spørsmål', new_question_path, class: 'btn btn-danger navbar-btn', style: 'padding: 5px 8px; color: #fff' %></li>
       <li><%= link_to 'Se spørsmål', questions_path, class: 'btn btn-danger navbar-btn', style: 'padding: 5px 8px; color: #fff; margin-left: 15px' %></li>
    

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Rediger profil', edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Logg ut", destroy_user_session_path, method: :delete %></li>
               
            </ul>
          </li>
          
        <% end %>
     
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>